---

name: Test

on:
  push:
    branches: [latest]
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
      - 'scripts/test_unit.sh'
      - 'scripts/test_func.sh'
  pull_request:
    branches: [latest]
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
      - 'scripts/test_unit.sh'
      - 'scripts/test_func.sh'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: |
          sudo apt install git
          go install gotest.tools/gotestsum@latest

      - name: Building Go Binary
        run: bash scripts/build.sh

      - name: Running Go Tests
        run: bash scripts/test_unit.sh

      - name: Running functional tests
        run: bash scripts/test_func.sh
